<?php
/**
 * MarketplaceAppRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use OpenAPI\Client\ObjectSerializer;

/**
 * MarketplaceAppRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MarketplaceAppRequest implements
    ModelInterface,
    ArrayAccess,
    \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = "MarketplaceAppRequest";

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        "name" => "string",
        "short_description" => "string",
        "long_description" => "string",
        "activation_webhook_url" => "string",
        "post_activation_redirect_uri" => "string",
        "viewer_plugins_urls" => "string[]",
        "webhook_secret" => "string",
        "settings_url" => "string",
        "tags" => "string[]",
        "logo" => "\SplFileObject",
        "file" => "\SplFileObject",
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        "name" => null,
        "short_description" => null,
        "long_description" => null,
        "activation_webhook_url" => "uri",
        "post_activation_redirect_uri" => "uri",
        "viewer_plugins_urls" => "uri",
        "webhook_secret" => null,
        "settings_url" => "uri",
        "tags" => null,
        "logo" => "binary",
        "file" => "binary",
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        "name" => false,
        "short_description" => false,
        "long_description" => false,
        "activation_webhook_url" => true,
        "post_activation_redirect_uri" => true,
        "viewer_plugins_urls" => true,
        "webhook_secret" => false,
        "settings_url" => true,
        "tags" => false,
        "logo" => true,
        "file" => true,
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(
        array $openAPINullablesSetToNull
    ): void {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        "name" => "name",
        "short_description" => "short_description",
        "long_description" => "long_description",
        "activation_webhook_url" => "activation_webhook_url",
        "post_activation_redirect_uri" => "post_activation_redirect_uri",
        "viewer_plugins_urls" => "viewer_plugins_urls",
        "webhook_secret" => "webhook_secret",
        "settings_url" => "settings_url",
        "tags" => "tags",
        "logo" => "logo",
        "file" => "file",
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        "name" => "setName",
        "short_description" => "setShortDescription",
        "long_description" => "setLongDescription",
        "activation_webhook_url" => "setActivationWebhookUrl",
        "post_activation_redirect_uri" => "setPostActivationRedirectUri",
        "viewer_plugins_urls" => "setViewerPluginsUrls",
        "webhook_secret" => "setWebhookSecret",
        "settings_url" => "setSettingsUrl",
        "tags" => "setTags",
        "logo" => "setLogo",
        "file" => "setFile",
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        "name" => "getName",
        "short_description" => "getShortDescription",
        "long_description" => "getLongDescription",
        "activation_webhook_url" => "getActivationWebhookUrl",
        "post_activation_redirect_uri" => "getPostActivationRedirectUri",
        "viewer_plugins_urls" => "getViewerPluginsUrls",
        "webhook_secret" => "getWebhookSecret",
        "settings_url" => "getSettingsUrl",
        "tags" => "getTags",
        "logo" => "getLogo",
        "file" => "getFile",
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists("name", $data ?? [], null);
        $this->setIfExists("short_description", $data ?? [], null);
        $this->setIfExists("long_description", $data ?? [], null);
        $this->setIfExists("activation_webhook_url", $data ?? [], null);
        $this->setIfExists("post_activation_redirect_uri", $data ?? [], null);
        $this->setIfExists("viewer_plugins_urls", $data ?? [], null);
        $this->setIfExists("webhook_secret", $data ?? [], null);
        $this->setIfExists("settings_url", $data ?? [], null);
        $this->setIfExists("tags", $data ?? [], null);
        $this->setIfExists("logo", $data ?? [], null);
        $this->setIfExists("file", $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(
        string $variableName,
        array $fields,
        $defaultValue
    ): void {
        if (
            self::isNullable($variableName) &&
            array_key_exists($variableName, $fields) &&
            is_null($fields[$variableName])
        ) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] =
            $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container["name"] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if (mb_strlen($this->container["name"]) > 256) {
            $invalidProperties[] =
                "invalid value for 'name', the character length must be smaller than or equal to 256.";
        }

        if (mb_strlen($this->container["name"]) < 1) {
            $invalidProperties[] =
                "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container["short_description"] === null) {
            $invalidProperties[] = "'short_description' can't be null";
        }
        if (mb_strlen($this->container["short_description"]) > 130) {
            $invalidProperties[] =
                "invalid value for 'short_description', the character length must be smaller than or equal to 130.";
        }

        if (mb_strlen($this->container["short_description"]) < 1) {
            $invalidProperties[] =
                "invalid value for 'short_description', the character length must be bigger than or equal to 1.";
        }

        if ($this->container["long_description"] === null) {
            $invalidProperties[] = "'long_description' can't be null";
        }
        if (mb_strlen($this->container["long_description"]) < 1) {
            $invalidProperties[] =
                "invalid value for 'long_description', the character length must be bigger than or equal to 1.";
        }

        if (
            !is_null($this->container["activation_webhook_url"]) &&
            mb_strlen($this->container["activation_webhook_url"]) > 1024
        ) {
            $invalidProperties[] =
                "invalid value for 'activation_webhook_url', the character length must be smaller than or equal to 1024.";
        }

        if (
            !is_null($this->container["post_activation_redirect_uri"]) &&
            mb_strlen($this->container["post_activation_redirect_uri"]) > 1024
        ) {
            $invalidProperties[] =
                "invalid value for 'post_activation_redirect_uri', the character length must be smaller than or equal to 1024.";
        }

        if (
            !is_null($this->container["webhook_secret"]) &&
            mb_strlen($this->container["webhook_secret"]) < 1
        ) {
            $invalidProperties[] =
                "invalid value for 'webhook_secret', the character length must be bigger than or equal to 1.";
        }

        if (
            !is_null($this->container["settings_url"]) &&
            mb_strlen($this->container["settings_url"]) > 1024
        ) {
            $invalidProperties[] =
                "invalid value for 'settings_url', the character length must be smaller than or equal to 1024.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container["name"];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (mb_strlen($name) > 256) {
            throw new \InvalidArgumentException(
                'invalid length for $name when calling MarketplaceAppRequest., must be smaller than or equal to 256.'
            );
        }
        if (mb_strlen($name) < 1) {
            throw new \InvalidArgumentException(
                'invalid length for $name when calling MarketplaceAppRequest., must be bigger than or equal to 1.'
            );
        }

        if (is_null($name)) {
            throw new \InvalidArgumentException(
                "non-nullable name cannot be null"
            );
        }

        $this->container["name"] = $name;

        return $this;
    }

    /**
     * Gets short_description
     *
     * @return string
     */
    public function getShortDescription()
    {
        return $this->container["short_description"];
    }

    /**
     * Sets short_description
     *
     * @param string $short_description short_description
     *
     * @return self
     */
    public function setShortDescription($short_description)
    {
        if (mb_strlen($short_description) > 130) {
            throw new \InvalidArgumentException(
                'invalid length for $short_description when calling MarketplaceAppRequest., must be smaller than or equal to 130.'
            );
        }
        if (mb_strlen($short_description) < 1) {
            throw new \InvalidArgumentException(
                'invalid length for $short_description when calling MarketplaceAppRequest., must be bigger than or equal to 1.'
            );
        }

        if (is_null($short_description)) {
            throw new \InvalidArgumentException(
                "non-nullable short_description cannot be null"
            );
        }

        $this->container["short_description"] = $short_description;

        return $this;
    }

    /**
     * Gets long_description
     *
     * @return string
     */
    public function getLongDescription()
    {
        return $this->container["long_description"];
    }

    /**
     * Sets long_description
     *
     * @param string $long_description long_description
     *
     * @return self
     */
    public function setLongDescription($long_description)
    {
        if (mb_strlen($long_description) < 1) {
            throw new \InvalidArgumentException(
                'invalid length for $long_description when calling MarketplaceAppRequest., must be bigger than or equal to 1.'
            );
        }

        if (is_null($long_description)) {
            throw new \InvalidArgumentException(
                "non-nullable long_description cannot be null"
            );
        }

        $this->container["long_description"] = $long_description;

        return $this;
    }

    /**
     * Gets activation_webhook_url
     *
     * @return string|null
     */
    public function getActivationWebhookUrl()
    {
        return $this->container["activation_webhook_url"];
    }

    /**
     * Sets activation_webhook_url
     *
     * @param string|null $activation_webhook_url activation_webhook_url
     *
     * @return self
     */
    public function setActivationWebhookUrl($activation_webhook_url)
    {
        if (
            !is_null($activation_webhook_url) &&
            mb_strlen($activation_webhook_url) > 1024
        ) {
            throw new \InvalidArgumentException(
                'invalid length for $activation_webhook_url when calling MarketplaceAppRequest., must be smaller than or equal to 1024.'
            );
        }

        if (is_null($activation_webhook_url)) {
            array_push(
                $this->openAPINullablesSetToNull,
                "activation_webhook_url"
            );
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search(
                "activation_webhook_url",
                $nullablesSetToNull
            );
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["activation_webhook_url"] = $activation_webhook_url;

        return $this;
    }

    /**
     * Gets post_activation_redirect_uri
     *
     * @return string|null
     */
    public function getPostActivationRedirectUri()
    {
        return $this->container["post_activation_redirect_uri"];
    }

    /**
     * Sets post_activation_redirect_uri
     *
     * @param string|null $post_activation_redirect_uri post_activation_redirect_uri
     *
     * @return self
     */
    public function setPostActivationRedirectUri($post_activation_redirect_uri)
    {
        if (
            !is_null($post_activation_redirect_uri) &&
            mb_strlen($post_activation_redirect_uri) > 1024
        ) {
            throw new \InvalidArgumentException(
                'invalid length for $post_activation_redirect_uri when calling MarketplaceAppRequest., must be smaller than or equal to 1024.'
            );
        }

        if (is_null($post_activation_redirect_uri)) {
            array_push(
                $this->openAPINullablesSetToNull,
                "post_activation_redirect_uri"
            );
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search(
                "post_activation_redirect_uri",
                $nullablesSetToNull
            );
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container[
            "post_activation_redirect_uri"
        ] = $post_activation_redirect_uri;

        return $this;
    }

    /**
     * Gets viewer_plugins_urls
     *
     * @return string[]|null
     */
    public function getViewerPluginsUrls()
    {
        return $this->container["viewer_plugins_urls"];
    }

    /**
     * Sets viewer_plugins_urls
     *
     * @param string[]|null $viewer_plugins_urls viewer_plugins_urls
     *
     * @return self
     */
    public function setViewerPluginsUrls($viewer_plugins_urls)
    {
        if (is_null($viewer_plugins_urls)) {
            array_push($this->openAPINullablesSetToNull, "viewer_plugins_urls");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("viewer_plugins_urls", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["viewer_plugins_urls"] = $viewer_plugins_urls;

        return $this;
    }

    /**
     * Gets webhook_secret
     *
     * @return string|null
     */
    public function getWebhookSecret()
    {
        return $this->container["webhook_secret"];
    }

    /**
     * Sets webhook_secret
     *
     * @param string|null $webhook_secret webhook_secret
     *
     * @return self
     */
    public function setWebhookSecret($webhook_secret)
    {
        if (!is_null($webhook_secret) && mb_strlen($webhook_secret) < 1) {
            throw new \InvalidArgumentException(
                'invalid length for $webhook_secret when calling MarketplaceAppRequest., must be bigger than or equal to 1.'
            );
        }

        if (is_null($webhook_secret)) {
            throw new \InvalidArgumentException(
                "non-nullable webhook_secret cannot be null"
            );
        }

        $this->container["webhook_secret"] = $webhook_secret;

        return $this;
    }

    /**
     * Gets settings_url
     *
     * @return string|null
     */
    public function getSettingsUrl()
    {
        return $this->container["settings_url"];
    }

    /**
     * Sets settings_url
     *
     * @param string|null $settings_url this URL will be called with query params ?cloud_id=
     *
     * @return self
     */
    public function setSettingsUrl($settings_url)
    {
        if (!is_null($settings_url) && mb_strlen($settings_url) > 1024) {
            throw new \InvalidArgumentException(
                'invalid length for $settings_url when calling MarketplaceAppRequest., must be smaller than or equal to 1024.'
            );
        }

        if (is_null($settings_url)) {
            array_push($this->openAPINullablesSetToNull, "settings_url");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("settings_url", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["settings_url"] = $settings_url;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]|null
     */
    public function getTags()
    {
        return $this->container["tags"];
    }

    /**
     * Sets tags
     *
     * @param string[]|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException(
                "non-nullable tags cannot be null"
            );
        }

        $this->container["tags"] = $tags;

        return $this;
    }

    /**
     * Gets logo
     *
     * @return \SplFileObject|null
     */
    public function getLogo()
    {
        return $this->container["logo"];
    }

    /**
     * Sets logo
     *
     * @param \SplFileObject|null $logo logo
     *
     * @return self
     */
    public function setLogo($logo)
    {
        if (is_null($logo)) {
            array_push($this->openAPINullablesSetToNull, "logo");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("logo", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["logo"] = $logo;

        return $this;
    }

    /**
     * Gets file
     *
     * @return \SplFileObject|null
     */
    public function getFile()
    {
        return $this->container["file"];
    }

    /**
     * Sets file
     *
     * @param \SplFileObject|null $file file
     *
     * @return self
     */
    public function setFile($file)
    {
        if (is_null($file)) {
            array_push($this->openAPINullablesSetToNull, "file");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("file", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["file"] = $file;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
