<?php
/**
 * Model
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use OpenAPI\Client\ObjectSerializer;

/**
 * Model Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Model implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = "Model";

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        "id" => "int",
        "name" => "string",
        "type" => "string",
        "creator" => "User",
        "status" => "string",
        "source" => "string",
        "created_at" => "\DateTime",
        "updated_at" => "\DateTime",
        "document_id" => "int",
        "document" => "Document",
        "structure_file" => "string",
        "systems_file" => "string",
        "map_file" => "string",
        "gltf_file" => "string",
        "bvh_tree_file" => "string",
        "preview_file" => "string",
        "viewer_360_file" => "string",
        "xkt_file" => "string",
        "project_id" => "int",
        "world_position" => "float[]",
        "size_ratio" => "float",
        "errors" => "string[]",
        "warnings" => "string[]",
        "archived" => "bool",
        "version" => "string",
        "north_vector" => "float[][]",
        "recommanded_2d_angle" => "float",
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        "id" => null,
        "name" => null,
        "type" => null,
        "creator" => null,
        "status" => null,
        "source" => null,
        "created_at" => "date-time",
        "updated_at" => "date-time",
        "document_id" => null,
        "document" => null,
        "structure_file" => "uri",
        "systems_file" => "uri",
        "map_file" => "uri",
        "gltf_file" => "uri",
        "bvh_tree_file" => "uri",
        "preview_file" => "uri",
        "viewer_360_file" => "uri",
        "xkt_file" => "uri",
        "project_id" => null,
        "world_position" => "double",
        "size_ratio" => "double",
        "errors" => null,
        "warnings" => null,
        "archived" => null,
        "version" => null,
        "north_vector" => "double",
        "recommanded_2d_angle" => "double",
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        "id" => false,
        "name" => true,
        "type" => false,
        "creator" => false,
        "status" => false,
        "source" => false,
        "created_at" => false,
        "updated_at" => false,
        "document_id" => true,
        "document" => false,
        "structure_file" => true,
        "systems_file" => true,
        "map_file" => true,
        "gltf_file" => true,
        "bvh_tree_file" => true,
        "preview_file" => true,
        "viewer_360_file" => true,
        "xkt_file" => true,
        "project_id" => true,
        "world_position" => true,
        "size_ratio" => true,
        "errors" => true,
        "warnings" => true,
        "archived" => false,
        "version" => true,
        "north_vector" => true,
        "recommanded_2d_angle" => true,
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(
        array $openAPINullablesSetToNull
    ): void {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        "id" => "id",
        "name" => "name",
        "type" => "type",
        "creator" => "creator",
        "status" => "status",
        "source" => "source",
        "created_at" => "created_at",
        "updated_at" => "updated_at",
        "document_id" => "document_id",
        "document" => "document",
        "structure_file" => "structure_file",
        "systems_file" => "systems_file",
        "map_file" => "map_file",
        "gltf_file" => "gltf_file",
        "bvh_tree_file" => "bvh_tree_file",
        "preview_file" => "preview_file",
        "viewer_360_file" => "viewer_360_file",
        "xkt_file" => "xkt_file",
        "project_id" => "project_id",
        "world_position" => "world_position",
        "size_ratio" => "size_ratio",
        "errors" => "errors",
        "warnings" => "warnings",
        "archived" => "archived",
        "version" => "version",
        "north_vector" => "north_vector",
        "recommanded_2d_angle" => "recommanded_2d_angle",
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        "id" => "setId",
        "name" => "setName",
        "type" => "setType",
        "creator" => "setCreator",
        "status" => "setStatus",
        "source" => "setSource",
        "created_at" => "setCreatedAt",
        "updated_at" => "setUpdatedAt",
        "document_id" => "setDocumentId",
        "document" => "setDocument",
        "structure_file" => "setStructureFile",
        "systems_file" => "setSystemsFile",
        "map_file" => "setMapFile",
        "gltf_file" => "setGltfFile",
        "bvh_tree_file" => "setBvhTreeFile",
        "preview_file" => "setPreviewFile",
        "viewer_360_file" => "setViewer360File",
        "xkt_file" => "setXktFile",
        "project_id" => "setProjectId",
        "world_position" => "setWorldPosition",
        "size_ratio" => "setSizeRatio",
        "errors" => "setErrors",
        "warnings" => "setWarnings",
        "archived" => "setArchived",
        "version" => "setVersion",
        "north_vector" => "setNorthVector",
        "recommanded_2d_angle" => "setRecommanded2dAngle",
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        "id" => "getId",
        "name" => "getName",
        "type" => "getType",
        "creator" => "getCreator",
        "status" => "getStatus",
        "source" => "getSource",
        "created_at" => "getCreatedAt",
        "updated_at" => "getUpdatedAt",
        "document_id" => "getDocumentId",
        "document" => "getDocument",
        "structure_file" => "getStructureFile",
        "systems_file" => "getSystemsFile",
        "map_file" => "getMapFile",
        "gltf_file" => "getGltfFile",
        "bvh_tree_file" => "getBvhTreeFile",
        "preview_file" => "getPreviewFile",
        "viewer_360_file" => "getViewer360File",
        "xkt_file" => "getXktFile",
        "project_id" => "getProjectId",
        "world_position" => "getWorldPosition",
        "size_ratio" => "getSizeRatio",
        "errors" => "getErrors",
        "warnings" => "getWarnings",
        "archived" => "getArchived",
        "version" => "getVersion",
        "north_vector" => "getNorthVector",
        "recommanded_2d_angle" => "getRecommanded2dAngle",
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_IFC = "IFC";
    public const TYPE_DWG = "DWG";
    public const TYPE_DXF = "DXF";
    public const TYPE_GLTF = "GLTF";
    public const TYPE_PDF = "PDF";
    public const TYPE_JPEG = "JPEG";
    public const TYPE_PNG = "PNG";
    public const TYPE_OBJ = "OBJ";
    public const TYPE_DAE = "DAE";
    public const TYPE_BFX = "BFX";
    public const TYPE_POINT_CLOUD = "POINT_CLOUD";
    public const TYPE_METABUILDING = "METABUILDING";
    public const SOURCE_UPLOAD = "UPLOAD";
    public const SOURCE_SPLIT = "SPLIT";
    public const SOURCE_MERGE = "MERGE";
    public const SOURCE_EXPORT = "EXPORT";
    public const SOURCE_OPTIMIZED = "OPTIMIZED";

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_IFC,
            self::TYPE_DWG,
            self::TYPE_DXF,
            self::TYPE_GLTF,
            self::TYPE_PDF,
            self::TYPE_JPEG,
            self::TYPE_PNG,
            self::TYPE_OBJ,
            self::TYPE_DAE,
            self::TYPE_BFX,
            self::TYPE_POINT_CLOUD,
            self::TYPE_METABUILDING,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSourceAllowableValues()
    {
        return [
            self::SOURCE_UPLOAD,
            self::SOURCE_SPLIT,
            self::SOURCE_MERGE,
            self::SOURCE_EXPORT,
            self::SOURCE_OPTIMIZED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists("id", $data ?? [], null);
        $this->setIfExists("name", $data ?? [], null);
        $this->setIfExists("type", $data ?? [], null);
        $this->setIfExists("creator", $data ?? [], null);
        $this->setIfExists("status", $data ?? [], null);
        $this->setIfExists("source", $data ?? [], null);
        $this->setIfExists("created_at", $data ?? [], null);
        $this->setIfExists("updated_at", $data ?? [], null);
        $this->setIfExists("document_id", $data ?? [], null);
        $this->setIfExists("document", $data ?? [], null);
        $this->setIfExists("structure_file", $data ?? [], null);
        $this->setIfExists("systems_file", $data ?? [], null);
        $this->setIfExists("map_file", $data ?? [], null);
        $this->setIfExists("gltf_file", $data ?? [], null);
        $this->setIfExists("bvh_tree_file", $data ?? [], null);
        $this->setIfExists("preview_file", $data ?? [], null);
        $this->setIfExists("viewer_360_file", $data ?? [], null);
        $this->setIfExists("xkt_file", $data ?? [], null);
        $this->setIfExists("project_id", $data ?? [], null);
        $this->setIfExists("world_position", $data ?? [], null);
        $this->setIfExists("size_ratio", $data ?? [], null);
        $this->setIfExists("errors", $data ?? [], null);
        $this->setIfExists("warnings", $data ?? [], null);
        $this->setIfExists("archived", $data ?? [], null);
        $this->setIfExists("version", $data ?? [], null);
        $this->setIfExists("north_vector", $data ?? [], null);
        $this->setIfExists("recommanded_2d_angle", $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(
        string $variableName,
        array $fields,
        $defaultValue
    ): void {
        if (
            self::isNullable($variableName) &&
            array_key_exists($variableName, $fields) &&
            is_null($fields[$variableName])
        ) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] =
            $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container["id"] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if (
            !is_null($this->container["name"]) &&
            mb_strlen($this->container["name"]) > 512
        ) {
            $invalidProperties[] =
                "invalid value for 'name', the character length must be smaller than or equal to 512.";
        }

        if ($this->container["type"] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (
            !is_null($this->container["type"]) &&
            !in_array($this->container["type"], $allowedValues, true)
        ) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container["type"],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container["creator"] === null) {
            $invalidProperties[] = "'creator' can't be null";
        }
        if ($this->container["status"] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getSourceAllowableValues();
        if (
            !is_null($this->container["source"]) &&
            !in_array($this->container["source"], $allowedValues, true)
        ) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'source', must be one of '%s'",
                $this->container["source"],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container["created_at"] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container["updated_at"] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        if ($this->container["document_id"] === null) {
            $invalidProperties[] = "'document_id' can't be null";
        }
        if ($this->container["document"] === null) {
            $invalidProperties[] = "'document' can't be null";
        }
        if ($this->container["structure_file"] === null) {
            $invalidProperties[] = "'structure_file' can't be null";
        }
        if ($this->container["systems_file"] === null) {
            $invalidProperties[] = "'systems_file' can't be null";
        }
        if ($this->container["map_file"] === null) {
            $invalidProperties[] = "'map_file' can't be null";
        }
        if ($this->container["gltf_file"] === null) {
            $invalidProperties[] = "'gltf_file' can't be null";
        }
        if ($this->container["bvh_tree_file"] === null) {
            $invalidProperties[] = "'bvh_tree_file' can't be null";
        }
        if ($this->container["preview_file"] === null) {
            $invalidProperties[] = "'preview_file' can't be null";
        }
        if ($this->container["viewer_360_file"] === null) {
            $invalidProperties[] = "'viewer_360_file' can't be null";
        }
        if ($this->container["xkt_file"] === null) {
            $invalidProperties[] = "'xkt_file' can't be null";
        }
        if ($this->container["project_id"] === null) {
            $invalidProperties[] = "'project_id' can't be null";
        }
        if (
            !is_null($this->container["world_position"]) &&
            count($this->container["world_position"]) > 3
        ) {
            $invalidProperties[] =
                "invalid value for 'world_position', number of items must be less than or equal to 3.";
        }

        if ($this->container["errors"] === null) {
            $invalidProperties[] = "'errors' can't be null";
        }
        if ($this->container["warnings"] === null) {
            $invalidProperties[] = "'warnings' can't be null";
        }
        if (
            !is_null($this->container["version"]) &&
            mb_strlen($this->container["version"]) > 256
        ) {
            $invalidProperties[] =
                "invalid value for 'version', the character length must be smaller than or equal to 256.";
        }

        if (
            !is_null($this->container["north_vector"]) &&
            count($this->container["north_vector"]) > 2
        ) {
            $invalidProperties[] =
                "invalid value for 'north_vector', number of items must be less than or equal to 2.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container["id"];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException(
                "non-nullable id cannot be null"
            );
        }

        $this->container["id"] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container["name"];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (!is_null($name) && mb_strlen($name) > 512) {
            throw new \InvalidArgumentException(
                'invalid length for $name when calling Model., must be smaller than or equal to 512.'
            );
        }

        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, "name");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("name", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["name"] = $name;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container["type"];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($type)) {
            throw new \InvalidArgumentException(
                "non-nullable type cannot be null"
            );
        }

        $this->container["type"] = $type;

        return $this;
    }

    /**
     * Gets creator
     *
     * @return User
     */
    public function getCreator()
    {
        return $this->container["creator"];
    }

    /**
     * Sets creator
     *
     * @param User $creator creator
     *
     * @return self
     */
    public function setCreator($creator)
    {
        if (is_null($creator)) {
            throw new \InvalidArgumentException(
                "non-nullable creator cannot be null"
            );
        }

        $this->container["creator"] = $creator;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container["status"];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException(
                "non-nullable status cannot be null"
            );
        }

        $this->container["status"] = $status;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string|null
     */
    public function getSource()
    {
        return $this->container["source"];
    }

    /**
     * Sets source
     *
     * @param string|null $source source
     *
     * @return self
     */
    public function setSource($source)
    {
        $allowedValues = $this->getSourceAllowableValues();
        if (!is_null($source) && !in_array($source, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'source', must be one of '%s'",
                    $source,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($source)) {
            throw new \InvalidArgumentException(
                "non-nullable source cannot be null"
            );
        }

        $this->container["source"] = $source;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container["created_at"];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException(
                "non-nullable created_at cannot be null"
            );
        }

        $this->container["created_at"] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container["updated_at"];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException(
                "non-nullable updated_at cannot be null"
            );
        }

        $this->container["updated_at"] = $updated_at;

        return $this;
    }

    /**
     * Gets document_id
     *
     * @return int
     */
    public function getDocumentId()
    {
        return $this->container["document_id"];
    }

    /**
     * Sets document_id
     *
     * @param int $document_id document_id
     *
     * @return self
     */
    public function setDocumentId($document_id)
    {
        if (is_null($document_id)) {
            array_push($this->openAPINullablesSetToNull, "document_id");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("document_id", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["document_id"] = $document_id;

        return $this;
    }

    /**
     * Gets document
     *
     * @return Document
     */
    public function getDocument()
    {
        return $this->container["document"];
    }

    /**
     * Sets document
     *
     * @param Document $document document
     *
     * @return self
     */
    public function setDocument($document)
    {
        if (is_null($document)) {
            throw new \InvalidArgumentException(
                "non-nullable document cannot be null"
            );
        }

        $this->container["document"] = $document;

        return $this;
    }

    /**
     * Gets structure_file
     *
     * @return string
     */
    public function getStructureFile()
    {
        return $this->container["structure_file"];
    }

    /**
     * Sets structure_file
     *
     * @param string $structure_file structure_file
     *
     * @return self
     */
    public function setStructureFile($structure_file)
    {
        if (is_null($structure_file)) {
            array_push($this->openAPINullablesSetToNull, "structure_file");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("structure_file", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["structure_file"] = $structure_file;

        return $this;
    }

    /**
     * Gets systems_file
     *
     * @return string
     */
    public function getSystemsFile()
    {
        return $this->container["systems_file"];
    }

    /**
     * Sets systems_file
     *
     * @param string $systems_file systems_file
     *
     * @return self
     */
    public function setSystemsFile($systems_file)
    {
        if (is_null($systems_file)) {
            array_push($this->openAPINullablesSetToNull, "systems_file");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("systems_file", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["systems_file"] = $systems_file;

        return $this;
    }

    /**
     * Gets map_file
     *
     * @return string
     */
    public function getMapFile()
    {
        return $this->container["map_file"];
    }

    /**
     * Sets map_file
     *
     * @param string $map_file map_file
     *
     * @return self
     */
    public function setMapFile($map_file)
    {
        if (is_null($map_file)) {
            array_push($this->openAPINullablesSetToNull, "map_file");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("map_file", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["map_file"] = $map_file;

        return $this;
    }

    /**
     * Gets gltf_file
     *
     * @return string
     */
    public function getGltfFile()
    {
        return $this->container["gltf_file"];
    }

    /**
     * Sets gltf_file
     *
     * @param string $gltf_file gltf_file
     *
     * @return self
     */
    public function setGltfFile($gltf_file)
    {
        if (is_null($gltf_file)) {
            array_push($this->openAPINullablesSetToNull, "gltf_file");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("gltf_file", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["gltf_file"] = $gltf_file;

        return $this;
    }

    /**
     * Gets bvh_tree_file
     *
     * @return string
     */
    public function getBvhTreeFile()
    {
        return $this->container["bvh_tree_file"];
    }

    /**
     * Sets bvh_tree_file
     *
     * @param string $bvh_tree_file bvh_tree_file
     *
     * @return self
     */
    public function setBvhTreeFile($bvh_tree_file)
    {
        if (is_null($bvh_tree_file)) {
            array_push($this->openAPINullablesSetToNull, "bvh_tree_file");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("bvh_tree_file", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["bvh_tree_file"] = $bvh_tree_file;

        return $this;
    }

    /**
     * Gets preview_file
     *
     * @return string
     */
    public function getPreviewFile()
    {
        return $this->container["preview_file"];
    }

    /**
     * Sets preview_file
     *
     * @param string $preview_file preview_file
     *
     * @return self
     */
    public function setPreviewFile($preview_file)
    {
        if (is_null($preview_file)) {
            array_push($this->openAPINullablesSetToNull, "preview_file");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("preview_file", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["preview_file"] = $preview_file;

        return $this;
    }

    /**
     * Gets viewer_360_file
     *
     * @return string
     */
    public function getViewer360File()
    {
        return $this->container["viewer_360_file"];
    }

    /**
     * Sets viewer_360_file
     *
     * @param string $viewer_360_file DEPRECATED: Use 'preview_file' instead.
     *
     * @return self
     */
    public function setViewer360File($viewer_360_file)
    {
        if (is_null($viewer_360_file)) {
            array_push($this->openAPINullablesSetToNull, "viewer_360_file");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("viewer_360_file", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["viewer_360_file"] = $viewer_360_file;

        return $this;
    }

    /**
     * Gets xkt_file
     *
     * @return string
     */
    public function getXktFile()
    {
        return $this->container["xkt_file"];
    }

    /**
     * Sets xkt_file
     *
     * @param string $xkt_file xkt_file
     *
     * @return self
     */
    public function setXktFile($xkt_file)
    {
        if (is_null($xkt_file)) {
            array_push($this->openAPINullablesSetToNull, "xkt_file");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("xkt_file", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["xkt_file"] = $xkt_file;

        return $this;
    }

    /**
     * Gets project_id
     *
     * @return int
     */
    public function getProjectId()
    {
        return $this->container["project_id"];
    }

    /**
     * Sets project_id
     *
     * @param int $project_id project_id
     *
     * @return self
     */
    public function setProjectId($project_id)
    {
        if (is_null($project_id)) {
            array_push($this->openAPINullablesSetToNull, "project_id");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("project_id", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["project_id"] = $project_id;

        return $this;
    }

    /**
     * Gets world_position
     *
     * @return float[]|null
     */
    public function getWorldPosition()
    {
        return $this->container["world_position"];
    }

    /**
     * Sets world_position
     *
     * @param float[]|null $world_position [x,y,z] array of the position of the local_placement in world coordinates
     *
     * @return self
     */
    public function setWorldPosition($world_position)
    {
        if (!is_null($world_position) && count($world_position) > 3) {
            throw new \InvalidArgumentException(
                'invalid value for $world_position when calling Model., number of items must be less than or equal to 3.'
            );
        }

        if (is_null($world_position)) {
            array_push($this->openAPINullablesSetToNull, "world_position");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("world_position", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["world_position"] = $world_position;

        return $this;
    }

    /**
     * Gets size_ratio
     *
     * @return float|null
     */
    public function getSizeRatio()
    {
        return $this->container["size_ratio"];
    }

    /**
     * Sets size_ratio
     *
     * @param float|null $size_ratio How many meters a unit represents
     *
     * @return self
     */
    public function setSizeRatio($size_ratio)
    {
        if (is_null($size_ratio)) {
            array_push($this->openAPINullablesSetToNull, "size_ratio");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("size_ratio", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["size_ratio"] = $size_ratio;

        return $this;
    }

    /**
     * Gets errors
     *
     * @return string[]
     */
    public function getErrors()
    {
        return $this->container["errors"];
    }

    /**
     * Sets errors
     *
     * @param string[] $errors List of errors that happened during IFC processing
     *
     * @return self
     */
    public function setErrors($errors)
    {
        if (is_null($errors)) {
            array_push($this->openAPINullablesSetToNull, "errors");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("errors", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["errors"] = $errors;

        return $this;
    }

    /**
     * Gets warnings
     *
     * @return string[]
     */
    public function getWarnings()
    {
        return $this->container["warnings"];
    }

    /**
     * Sets warnings
     *
     * @param string[] $warnings List of warnings that happened during IFC processing
     *
     * @return self
     */
    public function setWarnings($warnings)
    {
        if (is_null($warnings)) {
            array_push($this->openAPINullablesSetToNull, "warnings");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("warnings", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["warnings"] = $warnings;

        return $this;
    }

    /**
     * Gets archived
     *
     * @return bool|null
     */
    public function getArchived()
    {
        return $this->container["archived"];
    }

    /**
     * Sets archived
     *
     * @param bool|null $archived archived
     *
     * @return self
     */
    public function setArchived($archived)
    {
        if (is_null($archived)) {
            throw new \InvalidArgumentException(
                "non-nullable archived cannot be null"
            );
        }

        $this->container["archived"] = $archived;

        return $this;
    }

    /**
     * Gets version
     *
     * @return string|null
     */
    public function getVersion()
    {
        return $this->container["version"];
    }

    /**
     * Sets version
     *
     * @param string|null $version This field is only for information. Updating it won't impact the export.
     *
     * @return self
     */
    public function setVersion($version)
    {
        if (!is_null($version) && mb_strlen($version) > 256) {
            throw new \InvalidArgumentException(
                'invalid length for $version when calling Model., must be smaller than or equal to 256.'
            );
        }

        if (is_null($version)) {
            array_push($this->openAPINullablesSetToNull, "version");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("version", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["version"] = $version;

        return $this;
    }

    /**
     * Gets north_vector
     *
     * @return float[][]|null
     */
    public function getNorthVector()
    {
        return $this->container["north_vector"];
    }

    /**
     * Sets north_vector
     *
     * @param float[][]|null $north_vector This field is only for information. Updating it won't impact the export.
     *
     * @return self
     */
    public function setNorthVector($north_vector)
    {
        if (!is_null($north_vector) && count($north_vector) > 2) {
            throw new \InvalidArgumentException(
                'invalid value for $north_vector when calling Model., number of items must be less than or equal to 2.'
            );
        }

        if (is_null($north_vector)) {
            array_push($this->openAPINullablesSetToNull, "north_vector");
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("north_vector", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["north_vector"] = $north_vector;

        return $this;
    }

    /**
     * Gets recommanded_2d_angle
     *
     * @return float|null
     */
    public function getRecommanded2dAngle()
    {
        return $this->container["recommanded_2d_angle"];
    }

    /**
     * Sets recommanded_2d_angle
     *
     * @param float|null $recommanded_2d_angle This is the angle in clockwise degree to apply on the 2D to optimise the horizontality of objects. This field is only for information. Updating it won't impact the export.
     *
     * @return self
     */
    public function setRecommanded2dAngle($recommanded_2d_angle)
    {
        if (is_null($recommanded_2d_angle)) {
            array_push(
                $this->openAPINullablesSetToNull,
                "recommanded_2d_angle"
            );
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search("recommanded_2d_angle", $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container["recommanded_2d_angle"] = $recommanded_2d_angle;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
