<?php
/**
 * IfcApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use OpenAPI\Client\Configuration;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * IfcApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IfcApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addIfcErrorsDeprecated
     *
     * Add errors to model.
     *
     */
    public function testAddIfcErrorsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for bulkDeleteIfcClassificationsDeprecated
     *
     * Remove all classifications from model's elements.
     *
     */
    public function testBulkDeleteIfcClassificationsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for bulkDeleteIfcPropertiesDeprecated
     *
     * Delete many Property of a model.
     *
     */
    public function testBulkDeleteIfcPropertiesDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for bulkDeleteIfcPropertyDefinitionsDeprecated
     *
     * Delete many PropertyDefinitions of a model.
     *
     */
    public function testBulkDeleteIfcPropertyDefinitionsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for bulkDeleteIfcUnitsDeprecated
     *
     * Delete many Units of a model.
     *
     */
    public function testBulkDeleteIfcUnitsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for bulkDeletePropertySetDeprecated
     *
     * Delete many PropertySet of a model.
     *
     */
    public function testBulkDeletePropertySetDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for bulkFullUpdateElementsDeprecated
     *
     * Update many elements at once (only changing fields may be defined).
     *
     */
    public function testBulkFullUpdateElementsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for bulkFullUpdateIfcPropertyDeprecated
     *
     * Update some fields of many properties of a model.
     *
     */
    public function testBulkFullUpdateIfcPropertyDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for bulkRemoveClassificationsOfElementDeprecated
     *
     * Remove many classifications from an element.
     *
     */
    public function testBulkRemoveClassificationsOfElementDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for bulkRemoveDocumentsOfElementDeprecated
     *
     * Remove many documents from an element.
     *
     */
    public function testBulkRemoveDocumentsOfElementDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for bulkRemoveElementsFromClassificationDeprecated
     *
     * Remove the classifications from all elements.
     *
     */
    public function testBulkRemoveElementsFromClassificationDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for bulkUpdateElementsDeprecated
     *
     * Update many elements at once (all field must be defined).
     *
     */
    public function testBulkUpdateElementsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for bulkUpdateIfcPropertyDeprecated
     *
     * Update all fields of many properties of a model.
     *
     */
    public function testBulkUpdateIfcPropertyDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createAccessTokenDeprecated
     *
     * Create a token for this model.
     *
     */
    public function testCreateAccessTokenDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createBuildingDeprecated
     *
     * Create a building of a model.
     *
     */
    public function testCreateBuildingDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createBuildingPlanDeprecated
     *
     * Create a relation between a 2d model and a building.
     *
     */
    public function testCreateBuildingPlanDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createCheckerDeprecated
     *
     * Create a checker to a model.
     *
     */
    public function testCreateCheckerDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createCheckerResultDeprecated
     *
     * Create a CheckerResult.
     *
     */
    public function testCreateCheckerResultDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createClassificationElementRelationsDeprecated
     *
     * Create association between existing classification and existing element.
     *
     */
    public function testCreateClassificationElementRelationsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createClassificationsOfElementDeprecated
     *
     * Create one or many classifications to an element.
     *
     */
    public function testCreateClassificationsOfElementDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createElementDeprecated
     *
     * Create an element in the model.
     *
     */
    public function testCreateElementDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createElementPropertySetDeprecated
     *
     * Create a PropertySets to an element.
     *
     */
    public function testCreateElementPropertySetDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createElementPropertySetPropertyDefinitionDeprecated
     *
     * Create a Definition to a Property.
     *
     */
    public function testCreateElementPropertySetPropertyDefinitionDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createElementPropertySetPropertyDefinitionUnitDeprecated
     *
     * Create a Unit to a Definition.
     *
     */
    public function testCreateElementPropertySetPropertyDefinitionUnitDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createElementPropertySetPropertyDeprecated
     *
     * Create a property to a PropertySet.
     *
     */
    public function testCreateElementPropertySetPropertyDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createIfcDeprecated
     *
     * Make a PDF or Image file a Model.
     *
     */
    public function testCreateIfcDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createIfcPropertyDefinitionDeprecated
     *
     * Create a PropertyDefinition on the model.
     *
     */
    public function testCreateIfcPropertyDefinitionDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createIfcUnitDeprecated
     *
     * Create a Unit on a model.
     *
     */
    public function testCreateIfcUnitDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createLayerDeprecated
     *
     * Create a layer in the model.
     *
     */
    public function testCreateLayerDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createMetaBuildingDeprecated
     *
     * Create an empty 3D Model.
     *
     */
    public function testCreateMetaBuildingDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createPropertySetDeprecated
     *
     * Create one or many PropertySet.
     *
     */
    public function testCreatePropertySetDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createPropertySetElementRelationsDeprecated
     *
     * Create association between PropertySet and element.
     *
     */
    public function testCreatePropertySetElementRelationsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createRawElementsDeprecated
     *
     * Create elements in an optimized format.
     *
     */
    public function testCreateRawElementsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createSpaceDeprecated
     *
     * Create a space in the model.
     *
     */
    public function testCreateSpaceDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createStoreyDeprecated
     *
     * Create a storey of a model.
     *
     */
    public function testCreateStoreyDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createStoreyPlanDeprecated
     *
     * Create a relation between a 2d model and a storey.
     *
     */
    public function testCreateStoreyPlanDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createSystemDeprecated
     *
     * Create a system in the model.
     *
     */
    public function testCreateSystemDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createTilesetDeprecated
     *
     * Create the tileset of the model and upload all files.
     *
     */
    public function testCreateTilesetDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createZoneDeprecated
     *
     * Create a zone in the model.
     *
     */
    public function testCreateZoneDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for createZoneSpaceDeprecated
     *
     * Create a space in a zone.
     *
     */
    public function testCreateZoneSpaceDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteAccessTokenDeprecated
     *
     * Delete a token.
     *
     */
    public function testDeleteAccessTokenDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteBuildingDeprecated
     *
     * Delete a building of a model.
     *
     */
    public function testDeleteBuildingDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteBuildingPlanDeprecated
     *
     * Delete the relation between a 2d model and a building.
     *
     */
    public function testDeleteBuildingPlanDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteCheckerDeprecated
     *
     * Delete a checker of a model.
     *
     */
    public function testDeleteCheckerDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteCheckerResultDeprecated
     *
     * Delete a CheckerResult.
     *
     */
    public function testDeleteCheckerResultDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteElementDeprecated
     *
     * Delete an element of a model.
     *
     */
    public function testDeleteElementDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteIfcDeprecated
     *
     * Delete a model.
     *
     */
    public function testDeleteIfcDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteIfcPropertyDefinitionDeprecated
     *
     * Delete a PropertyDefinitions of a model.
     *
     */
    public function testDeleteIfcPropertyDefinitionDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteIfcPropertyDeprecated
     *
     * Delete a Property of a model.
     *
     */
    public function testDeleteIfcPropertyDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteIfcUnitDeprecated
     *
     * Delete a Unit of a model.
     *
     */
    public function testDeleteIfcUnitDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteIfcWithoutDocDeprecated
     *
     * Delete the Model without deleting the related document.
     *
     */
    public function testDeleteIfcWithoutDocDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteLayerDeprecated
     *
     * Delete a layer of a model.
     *
     */
    public function testDeleteLayerDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deletePropertySetDeprecated
     *
     * Delete a PropertySet of a model.
     *
     */
    public function testDeletePropertySetDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteSpaceDeprecated
     *
     * Delete a space.
     *
     */
    public function testDeleteSpaceDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteStoreyDeprecated
     *
     * Delete a storey of a model.
     *
     */
    public function testDeleteStoreyDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteStoreyPlanDeprecated
     *
     * Delete the relation between a 2d model and a storey.
     *
     */
    public function testDeleteStoreyPlanDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteSystemDeprecated
     *
     * Delete a system of a model.
     *
     */
    public function testDeleteSystemDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteZoneDeprecated
     *
     * Delete a zone of a model.
     *
     */
    public function testDeleteZoneDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for deleteZoneSpaceDeprecated
     *
     * Delete a space of a zone.
     *
     */
    public function testDeleteZoneSpaceDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for exportIfcDeprecated
     *
     * Export IFC.
     *
     */
    public function testExportIfcDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for fullUpdateElementDeprecated
     *
     * Update all fields of an element.
     *
     */
    public function testFullUpdateElementDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getAccessTokenDeprecated
     *
     * Retrieve one token created for this model.
     *
     */
    public function testGetAccessTokenDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getAccessTokensDeprecated
     *
     * Retrieve all tokens created for this model.
     *
     */
    public function testGetAccessTokensDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getBuildingDeprecated
     *
     * Retrieve a building of a model.
     *
     */
    public function testGetBuildingDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getBuildingPlanPositioningDeprecated
     *
     * Retrieve the postioning of the plan in the building.
     *
     */
    public function testGetBuildingPlanPositioningDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getBuildingsDeprecated
     *
     * Retrieve all buildings of a model.
     *
     */
    public function testGetBuildingsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getCheckerDeprecated
     *
     * Retrieve a checker of a model.
     *
     */
    public function testGetCheckerDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getCheckerResultDeprecated
     *
     * Retrieve one CheckerResult.
     *
     */
    public function testGetCheckerResultDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getCheckerResultsDeprecated
     *
     * Retrieve all CheckerResults.
     *
     */
    public function testGetCheckerResultsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getCheckersDeprecated
     *
     * Retrieve all checkers of a model.
     *
     */
    public function testGetCheckersDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getClassificationsOfElementDeprecated
     *
     * Retrieve all classifications of an element.
     *
     */
    public function testGetClassificationsOfElementDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getDocumentsOfElementDeprecated
     *
     * Retrieve all documents of an element.
     *
     */
    public function testGetDocumentsOfElementDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getElementDeprecated
     *
     * Retrieve an element of a model.
     *
     */
    public function testGetElementDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getElementLinkedDocumentsDeprecated
     *
     * Retrieve all documents linked to any element.
     *
     */
    public function testGetElementLinkedDocumentsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getElementPropertySetDeprecated
     *
     * Retrieve a PropertySet of an element.
     *
     */
    public function testGetElementPropertySetDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getElementPropertySetPropertiesDeprecated
     *
     * Retrieve all Properties of a PropertySet.
     *
     */
    public function testGetElementPropertySetPropertiesDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getElementPropertySetPropertyDefinitionDeprecated
     *
     * Retrieve a Definition of a Property.
     *
     */
    public function testGetElementPropertySetPropertyDefinitionDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getElementPropertySetPropertyDefinitionUnitDeprecated
     *
     * Retrieve a Unit of a Definition.
     *
     */
    public function testGetElementPropertySetPropertyDefinitionUnitDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getElementPropertySetPropertyDefinitionUnitsDeprecated
     *
     * Retrieve all Units of a Definition.
     *
     */
    public function testGetElementPropertySetPropertyDefinitionUnitsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getElementPropertySetPropertyDefinitionsDeprecated
     *
     * Retrieve all Definitions of a PropertySet.
     *
     */
    public function testGetElementPropertySetPropertyDefinitionsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getElementPropertySetPropertyDeprecated
     *
     * Retrieve a Property of a PropertySet.
     *
     */
    public function testGetElementPropertySetPropertyDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getElementPropertySetsDeprecated
     *
     * Retrieve all PropertySets of an element.
     *
     */
    public function testGetElementPropertySetsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getElementsDeprecated
     *
     * Retrieve all elements of a model.
     *
     */
    public function testGetElementsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getElementsFromClassificationDeprecated
     *
     * Retrieve all elements with the classification.
     *
     */
    public function testGetElementsFromClassificationDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getIfcClassificationsDeprecated
     *
     * Retrieve all classifications in a model.
     *
     */
    public function testGetIfcClassificationsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getIfcDeprecated
     *
     * Retrieve one model.
     *
     */
    public function testGetIfcDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getIfcMaterialDeprecated
     *
     * Retrieve a material of a model.
     *
     */
    public function testGetIfcMaterialDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getIfcMaterialsDeprecated
     *
     * Retrieve all materials of a model.
     *
     */
    public function testGetIfcMaterialsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getIfcPropertiesDeprecated
     *
     * Retrieve all Properties of a model.
     *
     */
    public function testGetIfcPropertiesDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getIfcPropertyDefinitionDeprecated
     *
     * Retrieve a PropertyDefinition of a model.
     *
     */
    public function testGetIfcPropertyDefinitionDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getIfcPropertyDefinitionsDeprecated
     *
     * Retrieve all PropertyDefinitions of a model.
     *
     */
    public function testGetIfcPropertyDefinitionsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getIfcPropertyDeprecated
     *
     * Retrieve a Property of a model.
     *
     */
    public function testGetIfcPropertyDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getIfcUnitDeprecated
     *
     * Retrieve a Unit of a model.
     *
     */
    public function testGetIfcUnitDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getIfcUnitsDeprecated
     *
     * Retrieve all Units of a model.
     *
     */
    public function testGetIfcUnitsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getIfcsDeprecated
     *
     * Retrieve all models.
     *
     */
    public function testGetIfcsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getLayerDeprecated
     *
     * Retrieve a layer of a model.
     *
     */
    public function testGetLayerDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getLayersDeprecated
     *
     * Retrieve all layers of a model.
     *
     */
    public function testGetLayersDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getMaterialDeprecated
     *
     * Retrieve a material of a model.
     *
     */
    public function testGetMaterialDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getMaterialsDeprecated
     *
     * Retrieve all materials of a model.
     *
     */
    public function testGetMaterialsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getProcessorHandlerDeprecated
     *
     * Retrieve a processor handler.
     *
     */
    public function testGetProcessorHandlerDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getProcessorHandlersDeprecated
     *
     * Get all processor handlers.
     *
     */
    public function testGetProcessorHandlersDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getPropertySetDeprecated
     *
     * Retrieve a PropertySet of a model.
     *
     */
    public function testGetPropertySetDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getPropertySetsDeprecated
     *
     * Retrieve all PropertySets of a model.
     *
     */
    public function testGetPropertySetsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getRawElementsDeprecated
     *
     * Retrieve all elements in a optimized format.
     *
     */
    public function testGetRawElementsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getSimpleElementDeprecated
     *
     * Retrieve an element of a model with a simple value representation.
     *
     */
    public function testGetSimpleElementDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getSimpleElementsDeprecated
     *
     * Retrieve all elements of a model with a simple value representation.
     *
     */
    public function testGetSimpleElementsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getSpaceDeprecated
     *
     * Retrieve one space of the model.
     *
     */
    public function testGetSpaceDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getSpacesDeprecated
     *
     * Retrieve all spaces of the model.
     *
     */
    public function testGetSpacesDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getStoreyDeprecated
     *
     * Retrieve a storey of a model.
     *
     */
    public function testGetStoreyDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getStoreyPlanPositioningDeprecated
     *
     * Retrieve the postioning of the plan in the storey.
     *
     */
    public function testGetStoreyPlanPositioningDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getStoreysDeprecated
     *
     * Retrieve all storeys of a model.
     *
     */
    public function testGetStoreysDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getSystemDeprecated
     *
     * Retrieve a system of a model.
     *
     */
    public function testGetSystemDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getSystemsDeprecated
     *
     * Retrieve all systems of a model.
     *
     */
    public function testGetSystemsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getTilesetDeprecated
     *
     * Retrieve the tileset of the model.
     *
     */
    public function testGetTilesetDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getZoneDeprecated
     *
     * Retrieve one zone of a model.
     *
     */
    public function testGetZoneDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getZoneSpaceDeprecated
     *
     * Retrieve one space of a zone.
     *
     */
    public function testGetZoneSpaceDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getZoneSpacesDeprecated
     *
     * Retrieve all spaces of a zone.
     *
     */
    public function testGetZoneSpacesDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for getZonesDeprecated
     *
     * Retrieve zones of a model.
     *
     */
    public function testGetZonesDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for launchNewCheckDeprecated
     *
     * Launch a new check on the model.
     *
     */
    public function testLaunchNewCheckDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for linkDocumentsOfElementDeprecated
     *
     * Link one or many documents to an element.
     *
     */
    public function testLinkDocumentsOfElementDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for listClassificationElementRelationsDeprecated
     *
     * List all associations between classifications and elements.
     *
     */
    public function testListClassificationElementRelationsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for mergeIfcsDeprecated
     *
     * Merge IFC files.
     *
     */
    public function testMergeIfcsDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for optimizeIfcDeprecated
     *
     * Optimize the IFC.
     *
     */
    public function testOptimizeIfcDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for removeAllElementPropertySetDeprecated
     *
     * Remove all property sets from element.
     *
     */
    public function testRemoveAllElementPropertySetDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for removeClassificationOfElementDeprecated
     *
     * Remove a classification from an element.
     *
     */
    public function testRemoveClassificationOfElementDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for removeDocumentOfElementDeprecated
     *
     * Remove a documents from an element.
     *
     */
    public function testRemoveDocumentOfElementDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for removeElementPropertySetDeprecated
     *
     * Remove a PropertySet from an element.
     *
     */
    public function testRemoveElementPropertySetDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for removeElementPropertySetPropertyDefinitionDeprecated
     *
     * Delete a Definition to a Property.
     *
     */
    public function testRemoveElementPropertySetPropertyDefinitionDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for removeElementPropertySetPropertyDefinitionUnitDeprecated
     *
     * Remove a Unit from a Definition.
     *
     */
    public function testRemoveElementPropertySetPropertyDefinitionUnitDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for removeElementPropertySetPropertyDeprecated
     *
     * Remove a property from a PropertySet.
     *
     */
    public function testRemoveElementPropertySetPropertyDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for removeElementsFromClassificationDeprecated
     *
     * Remove the classification from all elements.
     *
     */
    public function testRemoveElementsFromClassificationDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for reprocessIfcDeprecated
     *
     * Reprocess Model file.
     *
     */
    public function testReprocessIfcDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateAccessTokenDeprecated
     *
     * Update some fields of a token.
     *
     */
    public function testUpdateAccessTokenDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateBuildingDeprecated
     *
     * Update some fields of a building.
     *
     */
    public function testUpdateBuildingDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateBuildingPlanPositioningDeprecated
     *
     * Update the postioning of the plan in the building.
     *
     */
    public function testUpdateBuildingPlanPositioningDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateCheckerDeprecated
     *
     * Update some fields of a checker of a model.
     *
     */
    public function testUpdateCheckerDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateCheckerResultDeprecated
     *
     * Update some fields of a CheckerResult.
     *
     */
    public function testUpdateCheckerResultDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateElementDeprecated
     *
     * Update some fields of an element.
     *
     */
    public function testUpdateElementDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateElementPropertySetPropertyDeprecated
     *
     * Update a property from an element.
     *
     */
    public function testUpdateElementPropertySetPropertyDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateIfcDeprecated
     *
     * Update some fields of a model.
     *
     */
    public function testUpdateIfcDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateIfcFilesDeprecated
     *
     * Update models file (gltf, svg, structure, etc).
     *
     */
    public function testUpdateIfcFilesDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateIfcPropertyDefinitionDeprecated
     *
     * Update some fields of many PropertyDefinitions of a model.
     *
     */
    public function testUpdateIfcPropertyDefinitionDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateIfcPropertyDeprecated
     *
     * Update some fields of a Property.
     *
     */
    public function testUpdateIfcPropertyDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateIfcUnitDeprecated
     *
     * Update some fields of a Unit of a model.
     *
     */
    public function testUpdateIfcUnitDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateLayerDeprecated
     *
     * Update some fields of a layer.
     *
     */
    public function testUpdateLayerDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateOrderBuildingPlanDeprecated
     *
     * Update order of all plan of a building.
     *
     */
    public function testUpdateOrderBuildingPlanDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateOrderStoreyPlanDeprecated
     *
     * Update order of all plan of a storey.
     *
     */
    public function testUpdateOrderStoreyPlanDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateOrderStoreysDeprecated
     *
     * Update order of all storey of a model.
     *
     */
    public function testUpdateOrderStoreysDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateProcessorHandlerDeprecated
     *
     * Update the status of a processor handler.
     *
     */
    public function testUpdateProcessorHandlerDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updatePropertySetDeprecated
     *
     * Update some fields of a PropertySet.
     *
     */
    public function testUpdatePropertySetDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateSpaceDeprecated
     *
     * Update some fields of a space.
     *
     */
    public function testUpdateSpaceDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateStoreyDeprecated
     *
     * Update some fields of a storey.
     *
     */
    public function testUpdateStoreyDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateStoreyPlanPositioningDeprecated
     *
     * Update the postioning of the plan in the storey.
     *
     */
    public function testUpdateStoreyPlanPositioningDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateSystemDeprecated
     *
     * Update some fields of a system.
     *
     */
    public function testUpdateSystemDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateZoneDeprecated
     *
     * Update some fields of a zone.
     *
     */
    public function testUpdateZoneDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }

    /**
     * Test case for updateZoneSpaceDeprecated
     *
     * Update some fields of a space.
     *
     */
    public function testUpdateZoneSpaceDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete("Not implemented");
    }
}
